Form/DataTransformer/AuthorTransformer.php
<?php

/*
 * This file is part of the Integrated package.
 *
 * (c) e-Active B.V. <integrated@e-active.nl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Integrated\Bundle\ContentBundle\Form\DataTransformer;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Persistence\ManagerRegistry;
use Symfony\Component\Form\DataTransformerInterface;
use Integrated\Bundle\ContentBundle\Document\Content\Embedded\Author;

/**
 * @author Jurre de Jongh <jurre@e-active.nl>
 */
class AuthorTransformer implements DataTransformerInterface
{
    public function __construct(ManagerRegistry $mr)
    {
        $this->mr = $mr;
    }

    /**
     * {@inheritdoc}
     */
    public function transform($arrayCollection)
    {
        if ($arrayCollection == null) {
            return array();
        }

        $collection = array();

        foreach ($arrayCollection as $author) {
            if (!($author instanceof Author) || !$author->getPerson()) {
                continue;
            }

            $collection[] = array(
                'id'   => $author->getPerson()->getId(),
                'text' => (string) $author->getPerson(),
                'type' => $author->getType()
            );
        }

        return $collection;
    }

    /**
     * {@inheritdoc}
     */
    public function reverseTransform($array)
    {
        $mr         = $this->mr->getManager();
        $collection = array();

        if (is_array($array) && isset($array['persons'], $array['types']) && is_array($array['types'])) {
            foreach (explode(',', $array['persons']) as $person) {
                $result = $mr->getRepository('IntegratedContentBundle:Content\Relation\Person')->find($person);

                if ($result && isset($array['types'][$person])) {
                    $author = new \Integrated\Bundle\ContentBundle\Document\Content\Embedded\Author();
                    $author->setType($array['types'][$person]);
                    $author->setPerson($result);

                    $collection[] = $author;
                }
            }
        }

        return new ArrayCollection($collection);
    }
}

Form/DataTransformer/ChannelsTransformer.php
<?php

/*
 * This file is part of the Integrated package.
 *
 * (c) e-Active B.V. <integrated@e-active.nl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Integrated\Bundle\ContentBundle\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;

/**
 * @author Jan Sanne Mulder <jansanne@e-active.nl>
 */
class ChannelsTransformer implements DataTransformerInterface
{
    /**
     * @inheritdoc
     */
    public function transform($value)
    {
        $result = [
            'options'  => null,
            'defaults' => []
        ];

        if ($value === null || $value === '') {
            return $result;
        }

        if (isset($value['disabled'])) {
            $result['options'] = 'disabled';

            switch ((int) $value['disabled']){
                case 0:
                    $result['options'] = '';
                    break;

                case 1:
                    $result['options'] = 'hidden';
                    break;
            }
        }

        if (isset($value['defaults'])) {
            $defaults = [];

            // TODO filter out invalid channels

            foreach ($value['defaults'] as $channel) {
                $defaults[$channel['id']]['selected'] = true;
                $defaults[$channel['id']]['enforce'] = isset($channel['enforce']) ? (bool) $channel['enforce'] : false;
            }

            $result['defaults'] = $defaults;
        }

        return $result;
    }

    /**
     * @inheritdoc
     */
    public function reverseTransform($value)
    {
        $result = [
            'disabled' => 0,
            'defaults' => []
        ];

        if ($value === null || $value === '') {
            return $result;
        }

        switch ($value['options']) {
            case 'hidden':
                $result['disabled'] = 1;
                break;

            case 'disabled':
                $result['disabled'] = 2;
                break;
        }

        foreach ($value['defaults'] as $id => $options) {
            if ($options['selected']) {
                $result['defaults'][$id] = [
                    'id' => $id,
                    'enforce' => $options['enforce'] ? true : false
                ];
            }
        }

        $result['defaults'] = array_values($result['defaults']);

        return $result;
    }
}

Form/DataTransformer/ContentTypeField.php
<?php

/*
 * This file is part of the Integrated package.
 *
 * (c) e-Active B.V. <integrated@e-active.nl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Integrated\Bundle\ContentBundle\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;
use Integrated\Common\Form\Mapping\Metadata;
use Integrated\Bundle\ContentBundle\Document\ContentType\Embedded\Field;

/**
 * @author Jeroen van Leeuwen <jeroen@e-active.nl>
 */
class ContentTypeField implements DataTransformerInterface
{
    /**
     * @var Metadata\Field
     */
    private $contentTypeField;

    /**
     * @param Metadata\Field $contentTypeField
     */
    public function __construct(Metadata\Field $contentTypeField)
    {
        $this->contentTypeField = $contentTypeField;
    }

    /**
     * @param mixed $field
     * @return array|mixed
     */
    public function transform($field)
    {
        if ($field instanceof Field) {

            $options = $field->getOptions();

            return array(
                'enabled' => true,
                'required' => !empty($options['required'])
            );
        }

        return array();
    }

    /**
     * @param mixed $value
     * @return Field|mixed|null
     */
    public function reverseTransform($value)
    {
        if (is_array($value)) {
            if (!empty($value['enabled'])) {
                $field = new Field();

                $options = $this->contentTypeField->getOptions();
                $options['required'] = !empty($value['required']);

                $field->setName($this->contentTypeField->getName())
                      ->setType($this->contentTypeField->getType())
                      ->setOptions($options);

                return $field;
            }
        }

        return null;
    }
}

Form/DataTransformer/ContentTypeFieldCollection.php
<?php

/*
 * This file is part of the Integrated package.
 *
 * (c) e-Active B.V. <integrated@e-active.nl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Integrated\Bundle\ContentBundle\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;
use Integrated\Bundle\ContentBundle\Document\ContentType\Embedded\Field;

/**
 * @author Jeroen van Leeuwen <jeroen@e-active.nl>
 */
class ContentTypeFieldCollection implements DataTransformerInterface
{
    /**
     * @param mixed $fields
     * @return array $return
     */
    public function transform($fields)
    {
        $return = array();
        if (is_array($fields) || $fields instanceof \Traversable) {
            foreach ($fields as $field) {
                if ($field instanceof Field) {
                    $return[$field->getName()] = $field;
                }
            }
        }

        return $return;
    }

    /**
     * @param mixed $values
     * @return mixed|null
     */
    public function reverseTransform($values)
    {
        if (is_array($values) || $values instanceof \ArrayAccess) {
            foreach ($values as $key => $value) {
                if ($value === null) {
                    unset($values[$key]);
                }
            }
            return $values;
        }

        return null;
    }
}

Form/DataTransformer/CsvArray.php
<?php
/*
 * This file is part of the Integrated package.
 *
 * (c) e-Active B.V. <integrated@e-active.nl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Integrated\Bundle\ContentBundle\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;
use Symfony\Component\HttpFoundation\File\File;

/**
 * DataTransformer which handles comma separated values and return an array
 *
 * @author Jeroen van Leeuwen <jeroen@e-active.nl>
 */
class CsvArray implements DataTransformerInterface
{
    /**
     * @param mixed $value
     * @return mixed
     */
    public function transform($value)
    {
        if (empty($value)) {
            $value = array();
        }

        return implode(', ', $value);
    }

    /**
     * @param mixed $value
     * @return array
     */
    public function reverseTransform($value)
    {
        if (empty($value)) {
            $value = '';
        }

        return array_filter(array_map('trim', explode(',', $value)));
    }
}

Form/DataTransformer/FileTransformer.php
<?php

/*
 * This file is part of the Integrated package.
 *
 * (c) e-Active B.V. <integrated@e-active.nl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Integrated\Bundle\ContentBundle\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;

/**
 * @author Jeroen van Leeuwen <jeroen@e-active.nl>
 */
class FileTransformer implements DataTransformerInterface
{
    /**
     * {@inheritdoc}
     */
    public function transform($value)
    {
        return null;
    }

    /**
     * {@inheritdoc}
     */
    public function reverseTransform($value)
    {
        return $value;
    }
}

Form/DataTransformer/ImageTransformer.php
<?php

/*
 * This file is part of the Integrated package.
 *
 * (c) e-Active B.V. <integrated@e-active.nl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Integrated\Bundle\ContentBundle\Form\DataTransformer;

use Integrated\Bundle\ContentBundle\Document\Content\Image;
use Symfony\Component\Form\DataTransformerInterface;

use Doctrine\ODM\MongoDB\DocumentRepository;

/**
 * @author Ger Jan van den Bosch <gerjan@e-active.nl>
 */
class ImageTransformer implements DataTransformerInterface
{
    /**
     * @var DocumentRepository
     */
    private $repository;

    /**
     * @param DocumentRepository $repository
     */
    public function __construct(DocumentRepository $repository)
    {
        $this->repository = $repository;
    }

    /**
     * {@inheritdoc}
     */
    public function transform($image)
    {
        if ($image instanceof Image) {
            return $image->getId();
        }
    }

    /**
     * {@inheritdoc}
     */
    public function reverseTransform($id)
    {
        return $this->repository->find($id);
    }
}

Form/DataTransformer/MaxDateTimeTransformer.php
<?php

/*
 * This file is part of the Integrated package.
 *
 * (c) e-Active B.V. <integrated@e-active.nl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Integrated\Bundle\ContentBundle\Form\DataTransformer;

use Symfony\Component\Form\DataTransformerInterface;
use Integrated\Bundle\ContentBundle\Document\Content\Embedded\PublishTime;

/**
 * @author Ger Jan van den Bosch <gerjan@e-active.nl>
 */
class MaxDateTimeTransformer implements DataTransformerInterface
{
    /**
     * {@inheritdoc}
     */
    public function transform($dateTime)
    {
        if ($dateTime == new \DateTime(PublishTime::DATE_MAX)) {
            return; // hide max date
        }

        return $dateTime;
    }

    /**
     * {@inheritdoc}
     */
    public function reverseTransform($dateTime)
    {
        return $dateTime;
    }
}

Form/DataTransformer/Relations.php
<?php

/*
 * This file is part of the Integrated package.
 *
 * (c) e-Active B.V. <integrated@e-active.nl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Integrated\Bundle\ContentBundle\Form\DataTransformer;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Persistence\ObjectManager;

use Symfony\Component\Form\DataTransformerInterface;

use Integrated\Common\ContentType\Mapping\Metadata;
use Integrated\Common\Content\Relation\RelationInterface;

use Integrated\Bundle\ContentBundle\Document\Content\Embedded\Relation as EmbeddedRelation;

/**
 * @author Jeroen van Leeuwen <jeroen@e-active.nl>
 */
class Relations implements DataTransformerInterface
{
    /**
     * @var string
     */
    const REPOSITORY = 'Integrated\Bundle\ContentBundle\Document\Content\Content';

    /**
     * @var RelationInterface[]
     */
    protected $relations;

    /**
     * @var ObjectManager
     */
    protected $om;

    /**
     * @param RelationInterface[] $relations
     * @param ObjectManager $om
     */
    public function __construct($relations, ObjectManager $om)
    {
        $this->relations = $relations;
        $this->om = $om;
    }

    /**
     * Transform an array with EmbeddedRelation to an array with relations containing comma separated references
     *
     * {@inheritdoc}
     */
    public function transform($value)
    {
        $return = array();
        if (is_array($value) || $value instanceof \Traversable) {

            foreach ($value as $embeddedRelation) {

                if ($embeddedRelation instanceof EmbeddedRelation) {

                    if ($relation = $this->getRelation($embeddedRelation->getRelationId())) {
                        $references = array();
                        foreach ($embeddedRelation->getReferences() as $content) {
                            $references[] = $content->getId();
                        }

                        $return[$relation->getId()] = implode(',', $references);
                    }
                }
            }
        }

        return $return;
    }

    /**
     * Transform an array with relations containing comma separated references to an ArrayCollection with
     * EmbeddedRelation
     *
     * {@inheritdoc}
     */
    public function reverseTransform($value)
    {
        $relations = new ArrayCollection();

        if (is_array($value)) {

            foreach ($value as $relationId => $references) {

                if ($relation = $this->getRelation($relationId)) {

                    $embeddedRelation = new EmbeddedRelation();
                    $embeddedRelation->setRelationId($relation->getId());
                    $embeddedRelation->setRelationType($relation->getType());

                    if (null !== $references) {

                        $references = array_filter(explode(',', $references));
                        foreach ($references as $reference) {

                            if ($content = $this->om->getRepository(self::REPOSITORY)->find($reference)) {
                                $embeddedRelation->addReference($content);
                            }
                        }

                        $relations->add($embeddedRelation);
                    }
                }
            }
        }

        return $relations;
    }

    /**
     * @param string $relationId
     * @return bool|RelationInterface
     */
    protected function getRelation($relationId)
    {
        foreach ($this->relations as $relation) {
            if ($relation->getId() == $relationId) {
                return $relation;
            }
        }

        return false;
    }
}

Form/Type/AuthorType.php
<?php

/*
 * This file is part of the Integrated package.
 *
 * (c) e-Active B.V. <integrated@e-active.nl>
 *
 * For the full copyright and license information, please view the LICENSE
 * file that was distributed with this source code.
 */

namespace Integrated\Bundle\ContentBundle\Form\Type;

use Doctrine\Common\Persistence\ManagerRegistry;
use Integrated\Bundle\ContentBundle\Form\DataTransformer\AuthorTransformer;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;

/**
 * @author Jurre de Jongh <jurre@e-active.nl>
 */
class AuthorType extends AbstractType
{
    /**
     * @var ManagerRegistry
     */
    private $mr;

    /**
     * @param ManagerRegistry $mr
     */
    public function __construct(ManagerRegistry $mr)
    {
        $this->mr = $mr;
    }

    /**
     * {@inheritdoc}
     */
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $transformer = new AuthorTransformer($this->mr);

        $builder->addModelTransformer($transformer);
    }

    /**
     * {@inheritdoc}
     */
    public function getParent()
    {
        return 'text';
    }

    /**
     * {@inheritdoc}
     */
    public function getName()
    {
        return 'integrated_author';
    }
}

Resources/views/Form/form_div_layout.html.twig
{% use "IntegratedFormTypeBundle:Form:form_div_layout.html.twig" %}
{% use "IntegratedBlockBundle:Form:form_div_layout.html.twig" %}

{% block content_type_field_collection_widget %}
{% spaceless %}
    <table class="table">
        <thead>
        <tr>
            <th width="40%">{% trans %}Fields{% endtrans %}</th>
            <th>{% trans %}Required{% endtrans %}</th>
        </tr>
        </thead>
        <tbody>
        {% for field in form %}
            <tr>
                <td>
                    {% set element = field.enabled  %}
                    {{ block('content_type_checkbox_widget') }}
                </td>
                <td>
                    <div class="checkbox">
                        <label>{{ form_widget(field.required) }}</label>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endspaceless %}
{% endblock %}

{% block content_type_relation_collection_widget %}
{% spaceless %}
    <table class="table">
        <thead>
            <tr>
                <th width="40%">{% trans %}Content type{% endtrans %}</th>
                <th colspan="2">{% trans %}Relations{% endtrans %}</th>
                <th>{% trans %}Required{% endtrans %}</th>
            </tr>
        </thead>
        <tbody>
        {% for relation in form %}
            <tr>
                <td>
                    {% set element = relation.enabled  %}
                    {{ block('content_type_checkbox_widget') }}
                </td>
                <td>
                    {% set element = relation.multiple.0  %}
                    {{ block('content_type_radio_widget') }}
                </td>
                <td>
                    {% set element = relation.multiple.1  %}
                    {{ block('content_type_radio_widget') }}
                </td>
                <td>
                    <div class="checkbox">
                        {{ form_widget(relation.required) }}
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endspaceless %}
{% endblock %}

{% block translatable_text_widget %}
{% spaceless %}
    {% for field in form %}
        <div class="input-group" style="margin-bottom: 15px">
            <span class="input-group-addon">
                {{ field.vars.label }}
            </span>
            {{ form_widget(field) }}
        </div>
    {% endfor %}
{% endspaceless %}
{%  endblock %}

{% block translatable_textarea_widget %}
    {% spaceless %}
        {% for field in form %}
            <div class="input-group" style="margin-bottom: 15px">
            <span class="input-group-addon">
                {{ field.vars.label }}
            </span>
                {{ form_widget(field) }}
            </div>
        {% endfor %}
    {% endspaceless %}
{%  endblock %}

{% block content_type_checkbox_widget %}
    {% spaceless %}
        <div class="checkbox">
            {% if element.vars.label is not sameas(false) %}
                <label for="{{ element.vars.id }}">
                    <input id="{{ element.vars.id }}" name="{{ element.vars.full_name  }}" type="checkbox" {% if element.vars.value is defined %} value="{{ element.vars.value }}"{% endif %}{% if element.vars.checked %} checked="checked"{% endif %}/>
                    {{ element.vars.label|trans({}, translation_domain) }}
                </label>
            {% else %}
                {{ form_widget(field) }}
            {% endif %}
        </div>
    {% endspaceless %}
{% endblock %}

{% block content_type_radio_widget %}
    {% spaceless %}
        <div class="radio">
            {% if element.vars.label is not sameas(false) %}
                <label for="{{ element.vars.id }}">
                    <input id="{{ element.vars.id }}" name="{{ element.vars.full_name  }}" type="radio" {% if element.vars.value is defined %} value="{{ element.vars.value }}"{% endif %}{% if element.vars.checked %} checked="checked"{% endif %}/>
                    {{ element.vars.label|trans({}, translation_domain) }}
                </label>
            {% else %}
                {{ form_widget(field) }}
            {% endif %}
        </div>
    {% endspaceless %}
{% endblock %}

{% block content_relations_row %}
    <div class="form-relations" style="display: none;">
        {{ block('form_row') }}
    </div>
{% endblock %}

{% block integrated_file_row %}
    {% spaceless %}
        <div class="form-group{% if not form.vars.valid %} has-error{% endif %}">
            {{ form_label(form) }}
            <div class="col-sm-8">
                {% if (form.parent.vars.value.fileExtension is not empty) %}
                    <a href="{{ form.parent.vars.value.getWebPath() }}" target="_blank">
                        {% trans %}Download{% endtrans %}
                    </a>
                {% endif %}
                {{ form_widget(form) }}
                {{ form_errors(form) }}
            </div>
        </div>
    {% endspaceless %}
{% endblock %}

{% block integrated_image_row %}
    {% spaceless %}
        <div class="form-group{% if not form.vars.valid %} has-error{% endif %}">
            {{ form_label(form) }}
            <div class="col-sm-8">
                {% if (form.parent.vars.value.fileExtension is not empty) %}
                    <img style="max-width: 200px; margin-bottom: 10px;" src="{{ form.parent.vars.value.getWebPath() }}" />
                {% endif %}
                {{ form_widget(form) }}
                {{ form_errors(form) }}
            </div>
        </div>
    {% endspaceless %}
{% endblock %}

{% block content_type_channels_widget  %}
    {% for element in form %}
        {% set label_attr = element.vars.label_attr|merge({'class': (element.vars.label_attr.class|default('') ~ ' sr-only')|trim}) %}
        {{ form_row(element, {widget_col: '12', label_col: '12', label_attr: label_attr}) }}
    {% endfor %}
{% endblock %}

{% block content_type_channel_collection_widget %}
{% spaceless %}
    <table class="table">
        <colgroup>
            <col style="width:40%" />
            <col />
        </colgroup>

        <thead>
            <tr>
                <th>{% trans %}Default{% endtrans %}</th>
                <th>{% trans %}Enforce{% endtrans %}</th>
            </tr>
        </thead>

        <tbody>
        {% for channel in form %}
            <tr>
                <td>
                    {% set element = channel.selected  %}
                    {{ block('content_type_checkbox_widget') }}
                </td>
                <td>
                    <div class="checkbox">
                        <label>{{ form_widget(channel.enforce) }}</label>
                    </div>
                </td>
            </tr>
        {% endfor %}
        </tbody>
    </table>
{% endspaceless %}
{% endblock %}

{% block integrated_author_widget  %}

    <div class="input-group">
        <input type="hidden" id="{{ id }}" name="{{ full_name }}[persons]" class="col-md-12 integrated_select2" style="width: 100%; padding: 0;" />
        <span class="input-group-btn">
            <button id="types-btn" class="btn btn-default" type="button" style="padding: 5px 10px;"><span class="caret"></span></button>
        </span>
    </div>

    <div style="clear: both;"></div>

    <div id="authorTypes">
        {% if value is not empty %}
            {% for item in value %}
                <div id="type_{{ item.id }}" style="margin-top: 10px;" class="input-group input-group"><span class="input-group-addon">{{ item.text }}</span><input type="text" class="form-control type-text" name="{{ full_name }}[types][{{ item.id }}]" placeholder="Type" /></div>
            {% endfor %}
        {% endif %}
    </div>

    <script type="text/javascript">
        document.addEventListener("DOMContentLoaded", function(event) {

                $(".change-name-author").each(function() {
                    var id = $(this).attr('name');

                    $(this).attr('name', '{{ full_name }}[types][' + id + ']');
                });

                $("#{{ id }}").select2({
                    multiple: true,
                    ajax: {
                        url: "{{path('integrated_content_content_index', { 'contenttypes[]': 'person' })}}",
                        dataType: 'json',
                        data: function (term, page) {
                            return {
                                q: term,
                                _format: 'json',
                                page_limit: 10
                            };
                        },
                        results: function (data, page) {
                            return {
                                results: $.map(data.items, function (item) {
                                    return {
                                        text: item.title,
                                        id: item.id
                                    }
                                })
                            };
                        }
                    },
                    dropdownCssClass: "bigdrop"
                }).on("change", function(e) {
                    if(e.hasOwnProperty('added')) {
                        $("#authorTypes").append('<div id="type_' + e.added.id + '" style="margin-top: 10px;" class="input-group input-group"><span class="input-group-addon">' + e.added.text + '</span><input type="text" class="form-control type-text" name="{{ full_name }}[types][' + e.added.id + ']" placeholder="Type" /></div>');
                    }

                    if(e.hasOwnProperty('removed')) {
                        $("#type_" + e.removed.id).remove();
                    }
                });

                $('#types-btn').on("click", function(e) {
                    $('#authorTypes').toggle();
                });

                {% if value is not empty %}
                {% autoescape false %}
                $("#{{ id }}").select2('data', {{ value|json_encode() }});
                {% endautoescape %}
                {% endif %}
            });
    </script>
{% endblock %}

{% block integrated_publishtime_widget  %}
{% spaceless %}
    <div class="col-sm-6">
        <div class="form-group">
            {{ form_widget(form.startDate) }}
        </div>
    </div>

    <div class="col-sm-6">
        <div class="form-group">
            {{ form_widget(form.endDate) }}
        </div>
    </div>

    {{ form_errors(form.startDate) }}
    {{ form_errors(form.endDate) }}
{% endspaceless %}
{% endblock %}

{% block integrated_image_choice_widget  %}
{% spaceless %}
    {{ form(form) }}

    <script type="text/javascript">
        document.addEventListener('DOMContentLoaded', function(e) {

            $('#{{ form.vars.id }}').select2({
                ajax: {
                    url: '{{ path('integrated_content_content_index', { 'contenttypes[]': 'image' }) }}',
                    dataType: 'json',
                    data: function (term, page) {
                        return {
                            q: term,
                            page: page,
                            limit: 20,
                            _format: 'json'
                        };
                    },
                    results: function (data, page) {
                        return {
                            results: $.map(data.items, function (item) {
                                return {
                                    id: item.id,
                                    text: item.title
                                }
                            }),
                            more: (page * data.pagination.numItemsPerPage) < data.pagination.numFound
                        };
                    }
                },
                initSelection: function (element, callback) {
                    if (element.val()) {
                        $.ajax('{{ path('integrated_content_content_index') }}' + element.val() + '/show?_format=json', {
                            dataType: 'json'
                        }).done(function(data) {
                            callback({id: data.id, text: data.title});
                        });
                    }
                }
            });
        });
    </script>
{% endspaceless %}
{% endblock %}